# Generated by Django 4.1.7 on 2023-09-03 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0003_genre_mood_track_genre_mood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="mood",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mood_genres",
                to="capstone.mood",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genre_tracks",
                to="capstone.genre",
            ),
        ),
    ]
