# Generated by Django 4.1.7 on 2023-09-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0004_alter_genre_mood_alter_track_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="mood",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mood_genres",
                to="capstone.mood",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genre_tracks",
                to="capstone.genre",
            ),
        ),
    ]
