# Generated by Django 4.1.7 on 2023-09-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0008_remove_genre_mood_genre_moods"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="label",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="moods",
        ),
        migrations.AddField(
            model_name="mood",
            name="genres",
            field=models.ManyToManyField(related_name="moods", to="capstone.genre"),
        ),
        migrations.AlterField(
            model_name="mood",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="gdrive_id",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
