# Generated by Django 4.1.7 on 2023-09-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0009_rename_label_genre_name_remove_genre_moods_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
