# Generated by Django 4.1.7 on 2023-09-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("capstone", "0010_alter_genre_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "mood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_playlists",
                        to="capstone.mood",
                    ),
                ),
                (
                    "tracks",
                    models.ManyToManyField(
                        related_name="playlists", to="capstone.track"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="playlists",
            field=models.ManyToManyField(
                related_name="playlist_users", to="capstone.playlist"
            ),
        ),
    ]
