# Generated by Django 4.1.7 on 2024-06-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_track_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='audio',
        ),
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
