# Generated by Django 4.1.7 on 2024-06-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_remove_track_audio_track_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='gdrive_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
